bottleneck_dir: ${hydra:run.dir}/bottlenecks
metrics:
  - iops
logical_view_types: false
threshold: 45
trace_path: ./trace.darshan
type: DARSHAN
view_types:
  - file_name
  - proc_name
  - time_range
